export const LIFE_PHRASES = [
  "Aprender é transformar curiosidade em prática.",
  "Cada tentativa bem observada vira conhecimento.",
  "A clareza aparece quando a dúvida ganha método.",
  "Estudo consistente vale mais do que pressa.",
  "O erro bem entendido vira ferramenta.",
  "Ensinar é uma forma de organizar o que se aprendeu.",
  "Pequenas revisões constroem grandes entendimentos.",
  "Perguntar melhor é aprender melhor.",
  "A atenção de hoje sustenta a autonomia de amanhã.",
  "Quem pratica com calma aprende com mais profundidade.",
  "O conhecimento cresce quando é compartilhado.",
  "A repetição certa cria segurança intelectual.",
  "Entender o processo ajuda a confiar no resultado.",
  "Toda boa aula começa com escuta atenta.",
  "A curiosidade é o primeiro passo do raciocínio.",
  "O que é visto com frequência deixa de ser estranho.",
  "Disciplina de estudo abre espaço para mais repertório.",
  "O aprendizado amadurece quando encontra contexto.",
  "Uma dúvida bem feita já é metade da resposta.",
  "Quem registra o que aprendeu lembra com mais facilidade.",
  "O progresso didático costuma ser silencioso, mas sólido.",
  "Compreender é relacionar, não apenas memorizar.",
  "A prática dá forma ao que a teoria apresenta.",
  "Todo conceito ganha força quando vira exemplo.",
  "A reflexão organiza o que a experiência espalha.",
  "Estudar bem é aprender a pensar com mais nitidez.",
  "A paciência também é uma ferramenta de aprendizado.",
  "O conhecimento se torna útil quando encontra aplicação.",
  "O didático simplifica sem perder profundidade.",
  "Quem observa com atenção aprende com mais autonomia.",
  "A aula continua depois da aula, na revisão.",
  "Aprender é construir referência para as próximas etapas.",
  "O avanço real aparece no uso cotidiano do que foi estudado.",
  "Método dá ritmo ao entendimento.",
  "Um bom exemplo vale por muitos parágrafos.",
  "A conversa certa também ensina.",
  "Quando o conteúdo faz sentido, a memória agradece.",
  "O raciocínio melhora quando o processo é claro.",
  "Aprender é fazer ligações entre ideias.",
  "A autonomia nasce de repetição com propósito.",
  "Cada revisão afia a compreensão.",
  "Ensinar e aprender caminham juntos.",
  "Quem organiza o estudo encontra o foco mais rápido.",
  "A dúvida é um convite ao aprofundamento.",
  "Conhecimento útil é conhecimento que circula.",
  "A prática transforma informação em repertório.",
  "O aprender verdadeiro muda a forma de enxergar.",
  "Compreensão vem de método, não de sorte.",
  "O que foi entendido pode ser explicado com simplicidade.",
  "Boa didática faz o difícil parecer possível.",
];
